# Generated by Django 3.2 on 2021-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Класс иконок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описания сервиса'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ServiceImg/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описания категорий'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ServiceCategoryImg/', verbose_name='Фото'),
        ),
    ]
