# Generated by Django 3.2 on 2021-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_auto_20210411_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Класс иконок'),
        ),
    ]
