# Generated by Django 3.2 on 2021-04-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='serviceapp.servicecategory', verbose_name='Категория сервиса'),
        ),
    ]
