# Generated by Django 3.2 on 2021-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Фио')),
                ('description', models.TextField(verbose_name='О работнике')),
                ('img', models.ImageField(upload_to='Workers/', verbose_name='Фото')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
            ],
        ),
    ]
