# Generated by Django 3.2 on 2021-04-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название направлений')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка направлений')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание направлений')),
            ],
        ),
        migrations.CreateModel(
            name='DirectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категорий направлений')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка категорий направлений')),
                ('img', models.ImageField(blank=True, null=True, upload_to='DirectionCatImg/', verbose_name='Фото категорий направлений')),
                ('description', models.TextField(verbose_name='Описание категорий направлений')),
            ],
        ),
        migrations.CreateModel(
            name='DirectionImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='DirectionImg/', verbose_name='Фото направлений')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directionsimgs', to='workapp.direction', verbose_name='Фото направлений')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='workapp.directioncategory', verbose_name='Категорий направлений'),
        ),
    ]
