# Generated by Django 3.2 on 2021-04-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категорий')),
                ('img', models.ImageField(upload_to='NewsCategoryImg/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описания категорий')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время созданий')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок новости')),
                ('img', models.ImageField(upload_to='NewsImg/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описания новости')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время созданий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.newscategory', verbose_name='Категория новости')),
            ],
        ),
    ]
